Expoceep/Expoceep/Controllers/ConfiguracoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Expoceep.Bibliotecas;
using Microsoft.AspNetCore.Mvc;

namespace Expoceep.Controllers
{
    public class ConfiguracoesController : Controller
    {
        private LoginSession _loginSession;
        private IBackupDataBase _bkp;
        public ConfiguracoesController(LoginSession loginSession, IBackupDataBase bkp)
        {
            _loginSession = loginSession;
            _bkp = bkp;
        }
        public IActionResult Index()
        {
            if (_loginSession.GetUsuarioSession() != null)
                return View();
            else
                return this.RedirectToAction("Login", "Login");
        }
        public bool GerarBackup()
        {
            bool result = _bkp.GerarBackup();
            return result;
        }
        public object CarregarBackup()
        {
            Resultado result = _bkp.AplicarBackup();
            
            return result ;
        }
    }
}

Expoceep/Expoceep/Controllers/InicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Expoceep.Bibliotecas;
using Expoceep.DB;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Expoceep.Controllers
{
    public class InicioController : Controller
    {
        private ERPDatabaseContext context;
        private LoginSession _loginSession;
        private Sessao sessao;
        private readonly IToastNotification _toastNotification;
        public InicioController(ERPDatabaseContext contexto, LoginSession loginSession, IToastNotification toast, Sessao s)
        {
            context = contexto;
            _loginSession = loginSession;
            _toastNotification = toast;
            sessao = s;

        }

        public IActionResult Home()
        {

            if (_loginSession.GetUsuarioSession() != null)
            {
                if (!sessao.Existe("LOGADOMSG"))
                    _toastNotification.AddSuccessToastMessage("Bem Vindo " + _loginSession.GetUsuarioSession().Nome, new ToastrOptions() { Title = "Logado", TimeOut = 2000 });
                sessao.SalvarEmCache("LOGADOMSG", "true");
                return View();
            }
            else
                return this.RedirectToAction("Login", "Login");


            //var vl = new VerificadorDeSecao(new HttpContextAccessor()).VerificaLogin();
            //if (vl)
            //    return View();
            //else
            //    return RedirectToActionPermanent("Login", "Login");

        }

    }
}

Expoceep/Expoceep/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>




    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CakeRp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon.png">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Fonts.css" />
    @*<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />*@
    <link rel="stylesheet" href="~/lib/Toastr/toastr.css" />
    <link rel="stylesheet" href="~/lib/DataTable/datatables.min.css" />
    <link rel="stylesheet" href="~/lib/fontawesome-free-5.10.2-web/css/all.css" />
    <link rel="stylesheet" href="~/lib/select2/select2.css" />
    <link rel="stylesheet" href="~/lib/Chartjs/Chart.css" />
</head>
<body>
    <div class="loader-page" id="loaderpage" style="display:none">
        <div class="loader">
        </div>
        <p>Carregando...</p>
    </div>
    <header>

        @{

            if (Context.Session.TryGetValue("Login.Usuario", out byte[] a))
            {

                var UsuarioLogado = new ConversorDeObjetos().ConverterParaObject<Usuario>(Context.Session.GetString("UsuarioSession"));


                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
                    <div class="container">
                        <a class="navbar-brand" asp-area="" asp-controller="Inicio" asp-action="Home"><img src="~/img/lOGO/Logo_reto.png" style="height:10%;width:15%; padding:0px;margin-left:-100%;" /></a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                            <ul class="navbar-nav ">
                                <li class="nav-item">
                                    @{
                                        if (UsuarioLogado.NivelUsuario == NivelUsuario.CONTADOR)
                                        {

                                            <a class="nav-link text-dark" asp-area="" asp-controller="Vendas" asp-action="Index">Graficos</a>
                                        }
                                        else
                                        {

                                            <a class="nav-link text-dark" asp-area="" asp-controller="Vendas" asp-action="Index">Vendas</a>
                                        }

                                    }
                                </li>
                                @{
                                    if (UsuarioLogado.NivelUsuario != NivelUsuario.CONTADOR)
                                    {
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Cadastros" asp-action="Index">Cadastros</a>
                                        </li>
                                    }
                                }
                                <li class="nav-item dropdown  ">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        @Context.Session.GetString("USER")
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-left " aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-controller="Configuracoes" asp-action="Index" id="Config"><i class="fa fa-cog"></i> Configurações</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item pointer" id="Logout">Sair</a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            }
            else { }
        }



    </header>
    <div class="container-fluid m-0 p-0">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="">


            @RenderBody()
        </main>
        @await Component.InvokeAsync("NToastNotify")
    </div>
    @{

        if (a != null)
        {
            @*<footer class="border-top footer text-muted">
                    <div class="container">
                        &copy; 2019 - Expoceep - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </div>
                </footer>*@
        }
    }




    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery.mask.js"></script>
        <script src="~/lib/Toastr/toastr.min.js"></script>


        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>

    </environment>
    <script src="~/lib/jquery.maskMoney.js"></script>
    <script src="~/lib/DataTable/datatables.min.js"></script>
    <script src="~/lib/fontawesome-free-5.10.2-web/js/all.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/Parsley/parsley.min.js"></script>
    <script src="~/lib/select2/select2.js"></script>
    <script src="~/lib/Chartjs/Chart.js"></script>
    <script src="~/lib/FileSaver.js"></script>
    <script src="~/lib/jsPDF-1.3.2/dist/jspdf.min.js"></script>
    @*/////////////////////////////////////////////////*@
    @*AREA DE MENUS*@
    @*////////////////////////////////////////////////*@
    <script type="text/javascript" src="~/js/Login/Login.js"></script>
    <script type="text/javascript" src="~/js/Cadastrar/MenuCadastrar.js"></script>
    <script type="text/javascript" src="~/js/Configuracoes/MenuConfiguracoes.js"></script>
    <script type="text/javascript" src="~/js/Vendas/MenuVendas.js"></script>
    @*/////////////////////////////////////////////////*@
    @*FIM DA AREA DE MENUS*@
    @*/////////////////////////////////////////////////*@

    @RenderSection("Scripts", required: false)
</body>
</html>